In [ ]:
import sklearn.datasets
import numpy as np
import random
import pandas as pd
data = pd.read_csv(#dataset_path)
#X = data["data"]
#y = data["target"]
from numpy import mean
from numpy import std
from pandas import read_csv
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FeatureUnion
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD

In [ ]:

data1 = data.iloc[:, 7:48]
data2 = data.iloc[:, -1]
data = pd.concat([data1, data2], axis = 1)
data.head()

,position_id,attribute_value_ml_acceleration,attribute_value_ml_aerial_ability,attribute_value_ml_agility,attribute_value_ml_anticipation,attribute_value_ml_balance,attribute_value_ml_bravery,attribute_value_ml_command_of_area,attribute_value_ml_communication,attribute_value_ml_composure,...,attribute_value_ml_positioning,attribute_value_ml_positive_aggression,attribute_value_ml_reflexes,attribute_value_ml_stamina,attribute_value_ml_strength,attribute_value_ml_tackling,attribute_value_ml_team_work,attribute_value_ml_technique,attribute_value_ml_weakfoot,Label_Category_Num
0,2,42.505460,30.394741,42.505460,30.394741,42.505460,30.394741,NaN,30.394741,30.394741,...,42.505460,NaN,NaN,42.505460,42.505460,30.394741,30.394741,30.394741,NaN,0
1,10,42.505460,55.412505,42.505460,42.505460,55.412505,42.505460,NaN,42.505460,42.505460,...,55.412505,NaN,NaN,55.412505,55.412505,42.505460,55.412505,42.505460,NaN,0
2,5,55.412505,42.505460,55.412505,55.412505,55.412505,55.412505,NaN,55.412505,55.412505,...,42.505460,NaN,NaN,55.412505,42.505460,42.505460,55.412505,42.505460,NaN,0
3,3,70.506566,42.505460,55.412505,42.505460,55.412505,42.505460,NaN,30.394741,42.505460,...,42.505460,NaN,NaN,55.412505,42.505460,NaN,42.505460,42.505460,NaN,0
4,7,70.506566,42.505460,70.506566,55.412505,55.412505,55.412505,NaN,55.412505,55.412505,...,55.412505,42.50546,NaN,55.412505,55.412505,NaN,55.412505,55.412505,42.50546,0

In [ ]:
data = data.apply(lambda row: row.fillna(row.mean()), axis=1)
data.to_csv("mean.csv")
data.head()

,position_id,attribute_value_ml_acceleration,attribute_value_ml_aerial_ability,attribute_value_ml_agility,attribute_value_ml_anticipation,attribute_value_ml_balance,attribute_value_ml_bravery,attribute_value_ml_command_of_area,attribute_value_ml_communication,attribute_value_ml_composure,...,attribute_value_ml_positioning,attribute_value_ml_positive_aggression,attribute_value_ml_reflexes,attribute_value_ml_stamina,attribute_value_ml_strength,attribute_value_ml_tackling,attribute_value_ml_team_work,attribute_value_ml_technique,attribute_value_ml_weakfoot,Label_Category_Num
0,2.0,42.505460,30.394741,42.505460,30.394741,42.505460,30.394741,29.939151,30.394741,30.394741,...,42.505460,29.939151,29.939151,42.505460,42.505460,30.394741,30.394741,30.394741,29.939151,0.0
1,10.0,42.505460,55.412505,42.505460,42.505460,55.412505,42.505460,42.634567,42.505460,42.505460,...,55.412505,42.634567,42.634567,55.412505,55.412505,42.505460,55.412505,42.505460,42.634567,0.0
2,5.0,55.412505,42.505460,55.412505,55.412505,55.412505,55.412505,45.015976,55.412505,55.412505,...,42.505460,45.015976,45.015976,55.412505,42.505460,42.505460,55.412505,42.505460,45.015976,0.0
3,3.0,70.506566,42.505460,55.412505,42.505460,55.412505,42.505460,41.396999,30.394741,42.505460,...,42.505460,41.396999,41.396999,55.412505,42.505460,41.396999,42.505460,42.505460,41.396999,0.0
4,7.0,70.506566,42.505460,70.506566,55.412505,55.412505,55.412505,50.019199,55.412505,55.412505,...,55.412505,42.505460,50.019199,55.412505,55.412505,50.019199,55.412505,55.412505,42.505460,0.0

In [ ]:
data = data.apply(lambda column: column.fillna(column.mean()), axis=0)
data.to_csv("meancolumn.csv")
data.head()

,position_id,attribute_value_ml_acceleration,attribute_value_ml_aerial_ability,attribute_value_ml_agility,attribute_value_ml_anticipation,attribute_value_ml_balance,attribute_value_ml_bravery,attribute_value_ml_command_of_area,attribute_value_ml_communication,attribute_value_ml_composure,...,attribute_value_ml_positioning,attribute_value_ml_positive_aggression,attribute_value_ml_reflexes,attribute_value_ml_stamina,attribute_value_ml_strength,attribute_value_ml_tackling,attribute_value_ml_team_work,attribute_value_ml_technique,attribute_value_ml_weakfoot,Label_Category_Num
0,2.0,42.505460,30.394741,42.505460,30.394741,42.505460,30.394741,29.939151,30.394741,30.394741,...,42.505460,29.939151,29.939151,42.505460,42.505460,30.394741,30.394741,30.394741,29.939151,0.0
1,10.0,42.505460,55.412505,42.505460,42.505460,55.412505,42.505460,42.634567,42.505460,42.505460,...,55.412505,42.634567,42.634567,55.412505,55.412505,42.505460,55.412505,42.505460,42.634567,0.0
2,5.0,55.412505,42.505460,55.412505,55.412505,55.412505,55.412505,45.015976,55.412505,55.412505,...,42.505460,45.015976,45.015976,55.412505,42.505460,42.505460,55.412505,42.505460,45.015976,0.0
3,3.0,70.506566,42.505460,55.412505,42.505460,55.412505,42.505460,41.396999,30.394741,42.505460,...,42.505460,41.396999,41.396999,55.412505,42.505460,41.396999,42.505460,42.505460,41.396999,0.0
4,7.0,70.506566,42.505460,70.506566,55.412505,55.412505,55.412505,50.019199,55.412505,55.412505,...,55.412505,42.505460,50.019199,55.412505,55.412505,50.019199,55.412505,55.412505,42.505460,0.0

In [ ]:

# replace Inf values with NaN
data = data.fillna(method='ffill', axis=1)
data.to_csv("ffill.csv")
data.head()

,position_id,attribute_value_ml_acceleration,attribute_value_ml_aerial_ability,attribute_value_ml_agility,attribute_value_ml_anticipation,attribute_value_ml_balance,attribute_value_ml_bravery,attribute_value_ml_command_of_area,attribute_value_ml_communication,attribute_value_ml_composure,...,attribute_value_ml_positioning,attribute_value_ml_positive_aggression,attribute_value_ml_reflexes,attribute_value_ml_stamina,attribute_value_ml_strength,attribute_value_ml_tackling,attribute_value_ml_team_work,attribute_value_ml_technique,attribute_value_ml_weakfoot,Label_Category_Num
0,2.0,42.505460,30.394741,42.505460,30.394741,42.505460,30.394741,30.394741,30.394741,30.394741,...,42.505460,42.505460,42.505460,42.505460,42.505460,30.394741,30.394741,30.394741,30.394741,0.0
1,10.0,42.505460,55.412505,42.505460,42.505460,55.412505,42.505460,42.505460,42.505460,42.505460,...,55.412505,55.412505,55.412505,55.412505,55.412505,42.505460,55.412505,42.505460,42.505460,0.0
2,5.0,55.412505,42.505460,55.412505,55.412505,55.412505,55.412505,55.412505,55.412505,55.412505,...,42.505460,42.505460,42.505460,55.412505,42.505460,42.505460,55.412505,42.505460,42.505460,0.0
3,3.0,70.506566,42.505460,55.412505,42.505460,55.412505,42.505460,42.505460,30.394741,42.505460,...,42.505460,42.505460,42.505460,55.412505,42.505460,42.505460,42.505460,42.505460,42.505460,0.0
4,7.0,70.506566,42.505460,70.506566,55.412505,55.412505,55.412505,55.412505,55.412505,55.412505,...,55.412505,42.505460,42.505460,55.412505,55.412505,55.412505,55.412505,55.412505,42.505460,0.0

In [ ]:
#X, y = data.iloc[:, :-1], data.iloc[:, -1]
X = data.drop('Label_Category_Num',axis =1)
y = data['Label_Category_Num']
# minimally prepare dataset
X = X.astype('float')
y = LabelEncoder().fit_transform(y.astype('str'))
# transforms for the feature union
transforms = list()
transforms.append(('mms', MinMaxScaler()))
transforms.append(('ss', StandardScaler()))
transforms.append(('rs', RobustScaler()))
transforms.append(('qt', QuantileTransformer(n_quantiles=100, output_distribution='normal')))
transforms.append(('kbd', KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')))
transforms.append(('pca', PCA(n_components=7)))
transforms.append(('svd', TruncatedSVD(n_components=7)))
# create the feature union
fu = FeatureUnion(transforms)
# define the feature selection
rfe = RFE(estimator=LogisticRegression(solver='liblinear'), n_features_to_select=15)
# define the model
model = LogisticRegression(solver='liblinear')
# define the pipeline
steps = list()
steps.append(('fu', fu))
steps.append(('rfe', rfe))
steps.append(('m', model))
pipeline = Pipeline(steps=steps)
# define the cross-validation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.886 (0.019)